openapi: 3.0.3
info:
  title: Lesson API
  version: 1.0.0
paths:
  /lessons/create:
    post:
      summary: Создать новый урок
      description: Создает запись урока с данными пользователя и информацией о занятии
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LessonRequest'
      responses:
        '201':
          description: Урок успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LessonResponse'
        '400':
          description: Неверные данные запроса
components:
  schemas:
    LessonRequest:
      type: object
      required:
        - name
        - orderNumber
        - youtubeLink
        - email
        - telegram
      properties:
        name:
          type: string
          description: Как тебя зовут?
        orderNumber:
          type: string
          description: Номер заказа
        youtubeLink:
          type: string
          format: uri
          description: Ссылка на YouTube
        email:
          type: string
          format: email
          description: Email пользователя
        telegram:
          type: string
          description: Ссылка или ник Telegram
        languageLevel:
          type: string
          description: Выберите уровень языка
        grammarTopics:
          type: array
          items:
            type: string
          description: Какие грамматические темы интересны пользователю
    LessonResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        orderNumber:
          type: string
        youtubeLink:
          type: string
        email:
          type: string
        telegram:
          type: string
        languageLevel:
          type: string
        grammarTopics:
          type: array
          items:
            type: string
        createdAt:
          type: string
          format: date-time
          description: Время создания записи
